---
- hosts: all
  become: true

  vars_files:
    - vars.yml    
      
  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql

  tasks:
    - name: Ensure php-cli is installed for ubuntu
      apt:
        name: libapache2-mod-php 
        state: present

    - name: Delete existing index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy html file to web server
      template:
        src: index.php
        dest: /var/www/html/index.php