---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

  roles:
    - role: geerlingguy.haproxy
    - role: geerlingguy.firewall

  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']