firewall_allowed_tcp_ports:
  - "80"
  - "22"
firewall_state: started
firewall_enabled_at_boot: true
haproxy_frontend_bind_address: '*'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_servers:
  - name: app1
    address: 10.100.2.10:80
  - name: app2
    address: 10.100.2.11:80
