# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-21.04"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "web1" do |web1|
    web1.vm.hostname = "web1.lab"
    web1.vm.network "private_network", ip: "10.100.2.10"
    web1.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/web/main.yml"
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web2.lab"
    web2.vm.network "private_network", ip: "10.100.2.11"
    web2.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/web/main.yml"
    end
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db.lab"
    db.vm.network "private_network", ip: "10.100.2.12"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/db/main.yml"
    end
  end

  config.vm.define "lb" do |lb|
    lb.vm.hostname = "lb.lab"
    lb.vm.network "public_network", bridge: "wlp1s0"
    lb.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/haproxy/main.yml"
    end
  end
end